--- #YAML:1.0
name:               Mail-GPG
version:            1.0.7
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    GnuPG::Interface:   0
    Mail::Address:      0
    MIME::Entity:       5.419
    MIME::Parser:       5.419
    MIME::QuotedPrint:  2.2
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
