# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-GPG
version:      1.0.1
version_from: lib/Mail/GPG.pm
installdirs:  site
requires:
    GnuPG::Interface:              0
    Mail::Address:                 0
    MIME::Entity:                  0
    MIME::Parser:                  0
    MIME::QuotedPrint:             2.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
